version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:12-buster
      - image: hindsightsoftware/hotel-booking:latest

    steps:
      - checkout

      - restore_cache:
          key: hotel-booking-{{ checksum "package.json" }}

      - run:
          name: Download dependencies
          command: npm install

      - save_cache:
          paths:
            - ~/project/node_modules
            - ~/.npm
          key: hotel-booking-{{ checksum "package.json" }}

      - run:
          name: Wait for Backend connection
          command: |
            TIMEOUT=6
            until [ "$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:8080/)" -eq 200 ] || [ $TIMEOUT -eq 0 ]; do echo "Waiting for port 8080, timeout: $((TIMEOUT--))"; sleep 10; done
            if [[ "$TIMEOUT" -eq 0 ]]; then exit 1; fi
      
      - run:
          name: Unit Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test